### ISSUE TITLE
Generating templates for all tables for a schema that doesn't have any tables returns a misleading error message

### ISSUE THREAD

**Issue by jamie-burns** [Bungalow64/DBConfirm#46]
Try generating the templates for all tables for a schema that doesn't have any tables (or for a schema that doesn't exist itself), and the error returned is:

**Cannot find table: dbo2.***

For example, say I have a database with some tables in dbo, but where the dbo2 schema doesn't exist.  Running:

```
GenerateTemplatesSQLServer -d "DatabaseName" -t "*" -s "dbo2" 
```

This shows the error.

Really, this should say:

**Cannot find any tables in the dbo2 schema**

**Comment by Bungalow64** [comment]
This is included in 0.1.3
