### ISSUE TITLE
Update build process to locally publish NuGet packages and run tests against these

### ISSUE THREAD

**Issue by Bungalow64** [Bungalow64/DBConfirm#71]
See SlowFox: https://github.com/Bungalow64/SlowFox/blob/main/azure-pipelines.yml

Pack and push the NuGet packages to Azure DevOps feed, reference these packages in the SampleSolutions\NuGetTests projects, and let the tests run using these packages directly.

**Comment by jamie-burns** [comment]
This was completed as part of #86
